# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-quota\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2017-01-05 17:12+0100\n"
"PO-Revision-Date: 2016-01-14 11:26+0100\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/quota/tools.py:74
#, python-format
msgid "%s Days"
msgstr "%s Tage"

#: umc/python/quota/partition.py:58 umc/python/quota/partition.py:86
#: umc/python/quota/tools.py:131 umc/python/quota/tools.py:180
#: umc/python/quota/user.py:151
#, python-format
msgid "Could not open %s"
msgstr "Konnte %s nicht öffnen"

#: umc/python/quota/tools.py:185
msgid "Device could not be found"
msgstr "Partition konnte nicht gefunden werden"

#: umc/python/quota/tools.py:135
msgid "Device is not mounted"
msgstr "Partition ist nicht nicht eingebunden"

#: umc/python/quota/tools.py:72
msgid "Expired"
msgstr "Abgelaufen"

#: umc/python/quota/user.py:111
#, python-format
msgid ""
"Failed to modify quota settings for user %(user)s on partition %(partition)s."
msgstr ""
"Konnte Quota-Einstellungen für den Benutzer %(user)s auf der Partition "
"%(partition)s nicht modifizieren."

#: umc/python/quota/tools.py:295
msgid "Generating the quota information file failed"
msgstr "Erstellung der Quota-Informationsdatei ist fehlgeschlagen"

#: umc/python/quota/tools.py:239
msgid "Mounting the partition has failed"
msgstr "Einhängen der Partition ist fehlgeschlagen"

#: umc/python/quota/partition.py:102
msgid "No partition found"
msgstr "Keine Partition gefunden"

#: umc/python/quota/user.py:162
#, python-format
msgid "No partition found (%s)"
msgstr "Keine Partition gefunden (%s)"

#: umc/python/quota/tools.py:230
msgid "Operation was successful"
msgstr "Operation war erfolgreich"

#: umc/python/quota/tools.py:207
msgid "Quota already en/disabled"
msgstr "Quota bereits (de)aktiviert"

#: umc/python/quota/partition.py:117
msgid "Quota support successfully activated"
msgstr "Quota-Unterstützung erfolgreich aktiviert"

#: umc/python/quota/partition.py:133
msgid "Quota support successfully deactivated"
msgstr "Quota-Unterstützung erfolgreich deaktiviert"

#: umc/python/quota/tools.py:282
msgid "Remounting the partition has failed"
msgstr "Erneutes Einhängen der Partition ist fehlgeschlagen"

#: umc/python/quota/tools.py:242 umc/python/quota/tools.py:286
#: umc/python/quota/tools.py:299 umc/python/quota/tools.py:303
msgid "Restarting the quota services has failed"
msgstr "Neustart des Quota-Dienstes ist fehlgeschlagen"

#: umc/python/quota/user.py:160
#, python-format
msgid "The following partition is currently not mounted: %s"
msgstr "Die folgende Partition ist derzeit nicht eingebunden: %s"

#: umc/python/quota/user.py:158
#, python-format
msgid "The following partition is mounted without quota support: %s"
msgstr "Die folgende Partition ist ohne Quota-Unterstützung eingebunden: %s"

#: umc/python/quota/partition.py:99
msgid "This partition is currently not mounted"
msgstr "Die Partition ist derzeit nicht eingebunden"

#: umc/python/quota/tools.py:273
#, python-format
msgid ""
"To %s quota support for the root filesystem the system has to be rebooted."
msgstr ""
"Um quota-Unterstützung für das root-Dateisystem zu %s muss das System "
"neugestartet werden."

#: umc/python/quota/tools.py:223
msgid "Unknown filesystem"
msgstr "Unbekanntes Dateisystem"

#: umc/python/quota/tools.py:236
msgid "Unmounting the partition has failed"
msgstr "Aushängen der Partition ist fehlgeschlagen"

#: umc/python/quota/tools.py:272
msgid "disable"
msgstr "deaktivieren"

#: umc/python/quota/tools.py:272
msgid "enable"
msgstr "aktivieren"

#~ msgid "Successfully removed quota settings"
#~ msgstr "Quota-Einstellungen erfolgreich entfernt"

#~ msgid "Successfully set quota settings"
#~ msgstr "Quota-Einstellungen erfolgreich gesetzt"
