# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-passwordreset\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2019-02-27 14:55+0100\n"
"PO-Revision-Date: 2015-09-22 09:23+0200\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/passwordreset/send_plugin.py:56
msgid "????"
msgstr "????"

#: umc/python/passwordreset/__init__.py:440
msgid "Changing contact data failed."
msgstr "Ändern der Kontaktdaten fehlgeschlagen."

#: umc/python/passwordreset/__init__.py:186
msgid ""
"Either username or password is incorrect or you are not allowed to use this "
"service."
msgstr ""
"Entweder stimmen Benutzername und Passwort nicht oder Sie haben keine "
"Berechtigung diesen Dienst zu nutzen."

#: umc/python/passwordreset/sending/send_email.py:74
msgid "Email"
msgstr "E-Mail"

#: umc/python/passwordreset/__init__.py:584
msgid "Error sending token: {}"
msgstr "Fehler beim Versenden des Tokens: {}"

#: umc/python/passwordreset/sending/send_with_external.py:75
msgid "External"
msgstr "Extern"

#: umc/python/passwordreset/__init__.py:536
msgid "Failed to change password."
msgstr "Passwortänderung fehlgeschlagen."

#: umc/python/passwordreset/sending/send_sms.py:96
msgid "Mobile number"
msgstr "Mobilfunknummer"

#: umc/python/passwordreset/__init__.py:207
msgid ""
"No address has been stored, where a password recovery token could be sent to."
msgstr ""
"Es wurden keine Kontaktadressen gefunden, an die ein Token "
"(Sicherheitsschlüssel) zur Wiederherstellung des Password geschickt werden "
"könnte."

#: umc/python/passwordreset/__init__.py:201
msgid ""
"No contact information is stored for this user. Resetting the password is "
"not possible."
msgstr ""
"Für diesen Benutzer wurden keine Kontaktinformationen hinterlegt. Das "
"Zurücksetzen des Passworts ist daher nicht möglich."

#: umc/python/passwordreset/__init__.py:439
msgid "Successfully changed your contact data."
msgstr "Ihre Kontaktdaten wurden erfolgreich geändert."

#: umc/python/passwordreset/__init__.py:535
msgid "Successfully changed your password."
msgstr "Ihr Passwort wurde erfolgreich geändert."

#: umc/python/passwordreset/__init__.py:422
msgid "Successfully changed your profile data."
msgstr "Ihre Profildaten wurden erfolgreich geändert."

#: umc/python/passwordreset/__init__.py:489
msgid "Successfully send token."
msgstr "Der Token wurde erfolgreich versendet."

#: umc/python/passwordreset/__init__.py:178
msgid ""
"The allowed maximum number of connections to the server has been reached. "
"Please retry in {}."
msgstr ""
"Die erlaubte maximale Anzahl an Verbindungen zum Server wurde erreicht. "
"Bitte versuchen Sie es in {} erneut."

#: umc/python/passwordreset/__init__.py:421
#, python-format
msgid "The attributes could not be saved: %s"
msgstr "Die Attribute konnten nicht gespeichert werden: %s"

#: umc/python/passwordreset/__init__.py:623
msgid ""
"The configuration of the password reset service is not complete. The UCR "
"variables \"ad/reset/username\" and \"ad/reset/password\" need to be set "
"properly. Please inform an administration."
msgstr ""
"Die Konfiguration des Dienstes zum Passwort zurücksetzen ist nicht "
"abgeschlossen. Die UCR Variablen \"ad/reset/username\" und \"ad/reset/"
"password\" müssen auf einen geeigneten Wert gesetzt werden. Bitte "
"informieren Sie einen Administrator."

#: umc/python/passwordreset/__init__.py:88
#, python-format
msgid ""
"The connection to the server could not be established. Please try again "
"later. Error message was: %s"
msgstr ""
"Die Verbindungen zum Server konnte nicht aufgebaut werden. Bitte versuchen "
"Sie es später erneut. Fehlermeldung: %s"

#: umc/python/passwordreset/__init__.py:214
msgid "The password reset service is disabled via configuration registry."
msgstr ""
"Der Dienst zum Passwort zurücksetzen ist durch Configuration Registry "
"deaktiviert."

#: umc/python/passwordreset/__init__.py:194
msgid ""
"The token you supplied is either expired or invalid. Please request a new "
"one."
msgstr ""
"Der Token (Sicherheitsschlüssel) den Sie angegeben haben ist entweder "
"abgelaufen oder ungültig. Bitte fordern Sie einen neuen an."

#: umc/python/passwordreset/__init__.py:393
msgid "This value is required"
msgstr "Dieser Wert ist erforderlich"

#: umc/python/passwordreset/__init__.py:454
msgid "Unknown recovery method '{}'."
msgstr "Unbekannte Wiederherstellungsfunktion '{}'."

#: umc/python/passwordreset/__init__.py:324
msgid "Your picture"
msgstr "Ihr Foto"

#: umc/python/passwordreset/__init__.py:105
msgid "one hour"
msgstr "einer Stunde"

#: umc/python/passwordreset/__init__.py:100
msgid "one minute"
msgstr "einer Minute"

#: umc/python/passwordreset/__init__.py:107
msgid "{} hours"
msgstr "{} Stunden"

#: umc/python/passwordreset/__init__.py:103
msgid "{} minutes"
msgstr "{} Minuten"

#~ msgid ""
#~ "The attributes could not be saved. Ask your system administrator to make "
#~ "sure the fields you are trying to edit are allowed via the \"self-service/"
#~ "ldap_attributes\" UCR variable."
#~ msgstr ""
#~ "Die Attribute konnten nicht gespeichert werden. Bitten Sie Ihren "
#~ "Systemadministrator, sicherzustellen, dass die Felder, die Sie zu "
#~ "bearbeiten versuchen, über die UCR-Variable \"self-service/ldap_attributes"
#~ "\" erlaubt sind."
